version: '3'

services:
  api-crudgames-mysql: 
    image: bitnami/mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_DATABASE=crudgames